# Image-level Conditional Diffusion Model 配置

# 数据集配置
data:
  root_dir: "/home/eechengyang/Data/ISIC"
  image_size: 256
  batch_size: 4  # 每个GPU的批次大小
  num_workers: 4  # 每个GPU的数据加载线程数

# 分布式训练配置
distributed:
  backend: "gloo"
  init_method: "env://"
  world_size: -1  # 自动检测GPU数量
  rank: -1  # 自动检测
  local_rank: -1  # 自动检测

# 模型配置 - 兼容UNet2DModel
model:
  sample_size: 256  # 图像大小
  in_channels: 3  # 输入通道数
  out_channels: 3  # 输出通道数
  layers_per_block: 2  # 每个块的层数
  block_out_channels: [128, 256, 512, 512]  # 每个块的输出通道数
  down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D", "AttnDownBlock2D"]
  up_block_types: ["AttnUpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"]
  mid_block_type: "UNetMidBlock2DCrossAttn"
  cross_attention_dim: 768  # 交叉注意力维度
  attention_head_dim: 8  # 注意力头维度
  dropout: 0.1  # dropout率
  num_class_embeds: 7  # 类别嵌入数量
  class_embed_type: "timestep"  # 类别嵌入类型
  num_train_timesteps: 1000  # 训练时间步数
  beta_schedule: "linear"  # beta调度类型

# 训练配置
training:
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  num_timesteps: 1000
  guidance_scale: 7.5
  gradient_clip_val: 1.0
  mixed_precision: true
  accumulate_grad_batches: 1
  warmup_steps: 1000  # 学习率预热步数
  gradient_accumulation_steps: 1  # 梯度累积步数
  sync_bn: true  # 是否同步BatchNorm

# 采样配置
sampling:
  num_inference_steps: 50
  guidance_scale: 7.5
  num_samples_per_class: 1

# 评估配置
evaluation:
  metrics:
    - fid
    - inception_score
    - classification_accuracy
    - diversity
  eval_freq: 1000  # 每1000步评估一次
  num_eval_samples: 7  # 评估时生成的样本数

# 日志配置
logging:
  log_dir: "logs/image_diffusion"
  save_dir: "checkpoints/image_diffusion"
  log_every_n_steps: 100
  save_every_n_epochs: 5
  use_wandb: true
  wandb_project: "skin_lesion_synthesis"
  wandb_name: "image_diffusion" 