# Latent-level Conditional Diffusion Model 配置

# 数据集配置
data:
  root_dir: "data/raw"
  image_size: 256
  batch_size: 32
  num_workers: 4

# 自编码器配置
autoencoder:
  in_channels: 3
  out_channels: 3
  hidden_dims: [64, 128, 256, 512]
  latent_dim: 4
  image_size: 256
  use_attention: true
  dropout: 0.1

# 扩散模型配置
model:
  in_channels: 4  # latent_dim
  out_channels: 4
  model_channels: 256
  num_res_blocks: 2
  attention_resolutions: [16, 8]
  dropout: 0.1
  channel_mult: [1, 2, 2, 2]
  num_heads: 8
  num_classes: 7
  use_scale_shift_norm: true
  resblock_updown: true
  use_new_attention_order: false

# 训练配置
training:
  num_epochs: 100
  learning_rate: 1e-4
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  num_timesteps: 1000
  guidance_scale: 7.5
  gradient_clip_val: 1.0
  mixed_precision: true
  accumulate_grad_batches: 1
  # 自编码器训练配置
  ae_learning_rate: 2e-4
  ae_weight_decay: 0.01
  ae_beta1: 0.9
  ae_beta2: 0.999
  ae_num_epochs: 50

# 采样配置
sampling:
  num_inference_steps: 50
  guidance_scale: 7.5
  num_samples_per_class: 100

# 评估配置
evaluation:
  metrics:
    - fid
    - inception_score
    - classification_accuracy
    - diversity
    - reconstruction_error
  eval_freq: 1000
  num_eval_samples: 1000

# 日志配置
logging:
  log_dir: "logs/latent_diffusion"
  save_dir: "checkpoints/latent_diffusion"
  log_every_n_steps: 100
  save_every_n_epochs: 5
  use_wandb: true
  wandb_project: "skin_lesion_synthesis"
  wandb_name: "latent_diffusion" 